public enum Token {
    SEMICOLON, OP_PAREN, CL_PAREN, OP_CURLY, CL_CURLY,
    ASSIGN, PLUS, MINUS,
    LESS, LESS_EQ, GREATER, GREATER_EQ, EQUALS, DIFFERENT,
    CODE, SCAN, PRINT, IF, WHILE, INT, BOOLEAN, TRUE, FALSE,
    IDENTIFIER, NUMBER, ERROR, RW
}
